### ISSUE TITLE
Change from generous to strict p/r with warning

### ISSUE THREAD

**Issue by benhachey** [wikilinks/conll03_nel_eval#14]

**Comment by jnothman** [comment]
Is there a reason to maintain a warning or to keep the generous? Does either choice reflect any reported results?

**Comment by jnothman** [comment]
I don't think this is generally an issue with gold mentions, so unlikely to be reflected in published results.

**Comment by benhachey** [comment]
Yup. This doesn't affect any of our current comparisons, whether or not
gold mentions are used. Would do if we were macro-averaging across
document-level p/r.

**Comment by benhachey** [comment]
Done in 27c160943f0c53396205652844e4e2a65bf04c3d.
