### ISSUE TITLE
Data reading is sensitive to tabs - should it be?

### ISSUE THREAD

**Issue by wejradford** [wikilinks/conll03_nel_eval#15]
I get errors when I try to parse files with trailing tabs (but empty columns). We can fix this by using .strip() for all whitespace in ._parse_line(). Are there any side-effects for this?

**Comment by benhachey** [comment]
It's written for the conll format, which doesn't have empty columns. I
don't think there should be side-effects if you want to handle this.

On Wed, Jan 29, 2014 at 10:21 PM, wejradford notifications@github.comwrote:

> I get errors when I try to parse files with trailing tabs (but empty
> columns). We can fix this by using .strip() for all whitespace in ._parse_line().
> Are there any side-effects for this?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/benhachey/conll03_nel_eval/issues/15
> .

## 

Dr Ben Hachey
benhachey.info
+61 416 550 174

**Comment by wejradford** [comment]
I think we handle this now.
