### ISSUE TITLE
Different system and gold responses

### ISSUE THREAD

**Issue by wejradford** [wikilinks/conll03_nel_eval#16]
I get odd output trying to evaluate some data (in my home directory)

```
./cne ~wradford/sample.linked.tsv evaluate -g ~wradford/sample.gold.tsv
```

Gives

```
AssertionError: Got different system (82) and gold (80) true positives for doc 2489288
```

Any clues?

**Comment by benhachey** [comment]
I know where that's coming from. I assumed to counts should be the same for
gold-system and system-gold. Might not be true though. Can you send the
system and gold files you're running?

**Comment by benhachey** [comment]
Fixed. See 79e62f454f9becd59551c432bfb0092ac00fd06a.
