### ISSUE TITLE
Why the change to length-based end-mention logic?

### ISSUE THREAD

**Issue by benhachey** [wikilinks/conll03_nel_eval#17]
The new logic isn't robust to tokenization inconsistencies in input data, e.g.:

```
People  B       People's Daily  --NME--
's      I       People's Daily  --NME--
Daily   I       People's Daily  --NME--
```

Ok to go back to old logic?

**Comment by wejradford** [comment]
But fails on cases where they repeat.

```
Agent   B   Agent Morton & Morton
Morton  I   Agent Morton & Morton
&   I   Agent Morton & Morton
Morton  I   Agent Morton & Morton
```

I think the right approach is to yield the mention only
- when you see another "B"
- when you finish a sentence

What do you think?

**Comment by benhachey** [comment]
I thought entities like this were pretty unlikely so went for the simpler
implementation. I'll update to use B/I/O tags now.

On Thu, Jan 30, 2014 at 3:13 PM, wejradford notifications@github.comwrote:

> But fails on cases where they repeat.
> 
> Agent   B   Agent Morton & Morton
> Morton  I   Agent Morton & Morton
> &   I   Agent Morton & Morton
> Morton  I   Agent Morton & Morton
> 
> I think the right approach is to yield the mention only
> - when you see another "B"
> - when you finish a sentence
> 
> What do you think?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/benhachey/conll03_nel_eval/issues/17#issuecomment-33658941
> .

## 

Dr Ben Hachey
benhachey.info
+61 416 550 174

**Comment by benhachey** [comment]
Fixed. See 85725d522dde04ce9c55e1c0fc12e19dd1eeab0f.
