### ISSUE TITLE
Add submittable results

### ISSUE THREAD

**Issue by wejradford** [wikilinks/conll03_nel_eval#2]
These need to not include original data (assume that user has access to gold-standard).

**Comment by benhachey** [comment]
This is another two scripts:
- `cne sanitise SYSTEM`
- `cne rebuild -g GOLD SYSTEM`

**Comment by wejradford** [comment]
Added a first cut of this:

``` bash
./cne release outputs/radford-unsup-mapped.testb.txt > release
./cne merge -g outputs/gold-mapped.testb.txt release > merged
diff outputs/radford-unsup-mapped.testb.txt  merged
```

The format looks like:

```
1163testb SOCCER    2   3   Japan
1163testb SOCCER    7   8   China
1163testb SOCCER    12  14
1163testb SOCCER    16  19  United_Arab_Emirates
1163testb SOCCER    20  21  Japan
1163testb SOCCER    26  28  AFC_Asian_Cup
```

Issues are:
- we construct a `name` from the token texts in the data (a little dodgy)
- we don't handle sentence-crossing mentions
- it should handle scores, haven't tested yet...

@benhachey, @jnothman: what do you reckon?

**Comment by wejradford** [comment]
@benhachey, you mentioned that handling sentence-crossing mentions was a must-have. Is there any existing data that had this problem, or should I come up with a test-case?

**Comment by jnothman** [comment]
Is this a format known from elsewhere? I.e. with token offsets? What's the benefit of this over more-or-less `cut -f2,4` and a `paste` operation?

**Comment by wejradford** [comment]
Yeah, that's a reasonable point. I'm looking at adding character offset mode (we have received data in this format).
