### ISSUE TITLE
Filter output_a to only include mentions linked in output_b

### ISSUE THREAD

**Issue by wejradford** [wikilinks/conll03_nel_eval#30]
This should allow the Hoffart evaluations in #10.

The problem is that we can evaluate an AIDA system, getting less than 1 F-score, as this is not quite all gold mentions:

```
tp  fp  fn  precis  recall  fscore  match
4485    0   1131    1.000   0.799   0.888   strong_mention_match
```

This isn't going to match AIDA reported numbers, as it include mentions that were not evaluated (as they aren't linkable, with candidates in the `AIDA-means` resource).

My suggestion is to add a `-f DATA` option to filter, that removes mentions that do not align with `DATA`:

``` bash
./cne filter -f AIDA-gold-linkable-mentions.txt gold.txt > gold-linkable-mentions.txt
./cne filter -f AIDA-gold-linkable-mentions.txt system-gold-mentions.txt > system-gold-linkable-mentions.txt
```

Then, `evaluate` will produce comparable numbers:

``` bash
./cne evaluate -g gold-linkable-mentions.txt AIDA-gold-linkable-mentions.txt
./cne evaluate -g gold-linkable-mentions.txt system-gold-linkable-mentions.txt
```

@benhachey, @jnothman: what do you think?

**Comment by jnothman** [comment]
I think we've got too many meanings of filter, firstly.

I can't really understand what's going on. Can you give an example?

(And I'm watching so I don't need to be pinged in general.)

**Comment by wejradford** [comment]
`filter` could be renamed `prepare` or something that's more general purpose.

The key problem is that AIDA results are only evaluating disambiguation of KB entities, not extraction or search.

So, given a gold-standard:

```
Some B
Nil I
then
a
Standard B entity_id
Entity I entity_id
and
an
Alias B entity_id
```

An AIDA system may only supply the following (if it does not have a searcher that covers `Alias -> entity_id`:

```
Some
Nil
then
a
Standard B entity_id
Entity I entity_id
and
an
Alias
```

So, as well as considering gold mentions that link to the KB, we must filter those that appear in a search resource (hard), or appear in AIDA system output (easier).

**Comment by jnothman** [comment]
Okay. How about we call this setting "matched only". I am not sure whether
it works with the per-doc, per-mention, etc variants, though.

**Comment by wejradford** [comment]
So an option `-m`/`--match` that takes another output?

And `filter` -> `prepare`?

**Comment by jnothman** [comment]
No, I though would match between gold and syystem

**Comment by wejradford** [comment]
I prefer
- keeping all manipulation in `filter`, so add the "retain matching w.r.t. some output" logic there
- evaluation being as simple as possible (I'm placing value on anyone being able to read it and understand it)

What's the motivation for putting the "match" logic in evaluation?

**Comment by jnothman** [comment]
I thought you were suggesting that. Grep can do the match only,

**Comment by jnothman** [comment]
Fixed by grep, now 'filter-mentions'
