### ISSUE TITLE
data.CoNLLDialect is wrongly named

### ISSUE THREAD

**Issue by jnothman** [wikilinks/conll03_nel_eval#31]
This isn't the form of the CoNLL 03 data. We should give it its correct name...

**Comment by wejradford** [comment]
`CoNLL03NELDialect`?

**Comment by jnothman** [comment]
Problem is it's not Conll 03 dialect. That doesn't have doc ids, and has
POS and chunk tags.

**Comment by wejradford** [comment]
Well, it's the dialect used to represent a linked layer on top of the CoNLL03 dataset. It's all a little problematic, I agree...

**Comment by benhachey** [comment]
Could call it AidaDialect
