### ISSUE TITLE
Implement TAC NIL clustering measures

### ISSUE THREAD

**Issue by benhachey** [wikilinks/conll03_nel_eval#38]
CEAF, B-cubed, pairwise PRF

**Comment by jnothman** [comment]
These plus the MUC score as defined in Vilain et al (1995) are implemented
at https://github.com/jnothman/conll03_nel_eval/compare/ceaf albeit needing
more testing for edge cases. For instance Cai and Strube's (2010)
adjustments have not been included, and they have been belatedly in the
Pradhan et al. CoNLL scorer.

While implemented as metrics over sets, these have not yet been integrated
into the evaluator.

**Comment by benhachey** [comment]
Integration: #39 
Testing: #43
