### ISSUE TITLE
Add TAC reader

### ISSUE THREAD

**Issue by benhachey** [wikilinks/conll03_nel_eval#41]
Requires some refactoring in data. At least:
- Disentangle sentence annotations from mentions;
- Add entity type to mention.

Data itself can remain agnostic about offset type (token vs char).

**Comment by jnothman** [comment]
Do we want to support TAC < 2014?

**Comment by benhachey** [comment]
I believe the format is the same. The difference in TAC14 is just that the systems produce the query xml file as well as the linking annotations tab file.

**Comment by benhachey** [comment]
Done in [tac](../tree/tac) at 7ccff51200.
